image: mcr.microsoft.com/dotnet/core/sdk:2.2

stages:
    - build
    - test

before_script:
    - "dotnet restore"

build:
    stage: build
    script:
        - "dotnet build"
    only:
    - merge_requests
    - master
    - develop
    
test:
    stage: test
    script: 
        - "dotnet test"
    only:
    - merge_requests
    - master
    - develop
